apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rbps
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-rbps@sha256:64323dd49dbb9155ee636e68b6733e2ee5792ac03edda114bfd5dbae2e88c2b6
        name: my-nodejs
        resources: {}
status: {}
